version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: financial_manager
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=financial_manager
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    ports:
      - '3311:3306'
    networks:
        - mysql_network

volumes:
  data:

networks:
  mysql_network:
